# Generated by Django 3.2.5 on 2021-08-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Carregar imagem')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Interesse')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome do Participante')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organização/Projeto')),
                ('join', models.BooleanField(default=False, verbose_name='Colaborador Join?')),
                ('knowledge_level', models.CharField(choices=[('Nenhum', 'Nenhum'), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=15)),
                ('other_interest', models.CharField(blank=True, max_length=15, null=True, verbose_name='Outros interesses')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Atualizado em')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.image', verbose_name='Imagem')),
                ('interests', models.ManyToManyField(related_name='participant_interest', to='workshop.Interest', verbose_name='Interesses')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('email',)},
            },
        ),
    ]
