# Generated by Django 3.2.5 on 2021-08-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Interesse', 'verbose_name_plural': 'Interesses'},
        ),
    ]
