# Generated by Django 3.2.5 on 2021-07-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20210711_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome do Participante')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('knowledge_level', models.CharField(choices=[('0', 'Desconhece'), ('1', 'Básico'), ('2', 'Intermediário'), ('3', 'Avançado')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Atualizado em')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.image', verbose_name='Imagem')),
                ('interests', models.ManyToManyField(related_name='participant_interest', to='workshop.Interest', verbose_name='Interesses')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
