# Generated by Django 3.2.5 on 2021-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20210714_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organização/Projeto'),
        ),
    ]
