# Generated by Django 3.2.5 on 2021-07-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_eventparticipant_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='join',
            field=models.BooleanField(default=False, verbose_name='Colaborador Join?'),
        ),
    ]
