# Generated by Django 3.2.5 on 2021-07-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_eventparticipant_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='ip_address',
        ),
    ]
