# Generated by Django 3.2.5 on 2021-07-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_remove_eventparticipant_ip_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('email',)},
        ),
    ]
