# Generated by Django 3.2.5 on 2021-08-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_eventparticipant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='knowledge_level',
        ),
    ]
