# Generated by Django 3.2.5 on 2021-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_eventparticipant_knowledge_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='knowledge_level',
            field=models.CharField(choices=[('Nenhum', 'Nenhum'), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=15),
        ),
    ]
