# Generated by Django 3.2.5 on 2021-08-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_alter_eventparticipant_knowledge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='other_interest',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Outros interesses'),
        ),
    ]
